packages:
  - apps/api

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma

ignoredBuiltDependencies:
  - '@scarf/scarf'
allowBuilds:
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  prisma: set this to true or false
